FROM ubuntu:16.04

# This is the base dockerfile.

# Much of this dockerfile is based off of the rpy2 docker image found:
# https://hub.docker.com/r/rpy2/rpy2/~/dockerfile/

RUN \
  apt-get update -qq && \
  apt-get install -y lsb-release && \
  echo "deb http://archive.linux.duke.edu/cran/bin/linux/ubuntu $(lsb_release -sc)/" \
      >> /etc/apt/sources.list.d/added_repos.list && \
  apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9 && \
  apt-get update -qq && \
  apt-get install -y \
  ed \
  git \
  mercurial \
  libcairo-dev \
  libedit-dev \
  lsb-release \
  python3 \
  python3-pip \
  r-base \
  r-base-dev \
  libpq-dev \
  libxml2-dev \
  libssl-dev \
  libcurl4-openssl-dev \
  curl \
  wget && \
  rm -rf /var/lib/apt/lists/*

RUN groupadd user && useradd --create-home --home-dir /home/user -g user user
WORKDIR /home/user

ENV R_LIBS "/usr/local/lib/R/site-library"

COPY dependencies.R .
COPY install_ensg_pkgs.R .
COPY convert.R .
RUN Rscript dependencies.R

USER user

ENTRYPOINT []
